server.port=8080
server.address=0.0.0.0
server.forward-headers-strategy=framework

# --- CẤU HÌNH KẾT NỐI POSTGRESQL ---
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.bgmwwohtvcpfpwzhkbkx
spring.datasource.password=ft73#xYy/p5C!*X
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình Hibernate (tự động tạo bảng)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- CẤU HÌNH MAIL GỬI MÃ XÁC THỰC ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=9102005duybao@gmail.com
spring.mail.password=bnkhdnkyiwahdfxn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# OAUTH2 GOOGLE CONFIG (TODO: Thay ID và SECRET thật từ Google Cloud Console)
spring.security.oauth2.client.registration.google.client-id=456963635943-tp3a88rtgoj7dndc1fq1j6s3bnafoavu.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# Khóa bí mật cho JWT (Phải dài ít nhất 64 ký tự cho HS512)
jwt.secret=LC_Network_PBL5_Secret_Key_Super_Secure_Must_Be_At_Least_64_Bytes_Long_To_Be_Valid

# Cấu hình kích thước file tải lên
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
